### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by genjikowa** [iErcann/TwitchCompilationGenerator#1]
Hi.

How is the software configured?

There are missing files that are in the youtube video but not here.

**Comment by iErcann** [comment]
I have updated the project, it now creates the necessary folders automatically.
You have to create a Twitch application to get a client id: https://dev.twitch.tv/console/apps

For example: 
![image](https://user-images.githubusercontent.com/25112067/107284783-8f628280-6a5e-11eb-88e2-cab2733be04d.png)
 
 
Once you have installed Node.js and npm, clone the project and do: `npm i` 
Paste your client id in `config.js`
Run `node index.js` 

And it should work.

**Comment by genjikowa** [comment]
Thanks for your answer, I just saw the comment I don't know why I didn't get a notification to the mail, I'm using Windows 10 I have entered the id and when I run index.js I get an error, how should I run it? do I have to have something additional installed?

![imagen](https://user-images.githubusercontent.com/78709893/109180048-c89f3000-778a-11eb-8eb7-7d815ddb69a9.png)

![imagen](https://user-images.githubusercontent.com/78709893/109180130-dc4a9680-778a-11eb-8e15-09adc13883e3.png)

I am looking forward to your response.

**Comment by iErcann** [comment]
You have put your id in the wrong place, it should be something like this:

```
const client_id = "ywbtycvnyuebdaihwt5d87e7obgz51"

module.exports = { client_id };
```
You also have to add FFMPEG to your path.

**Comment by genjikowa** [comment]
I already have the ID set correctly, the path of the FFMPEG I have it in the system variables correctly but I still get the error. How should I run it on windows?

**Comment by iErcann** [comment]
Go to the project folder in your terminal and do:
 `node index.js`

**Comment by genjikowa** [comment]
i have a new error

![imagen](https://user-images.githubusercontent.com/78709893/109200717-3b1b0a80-77a1-11eb-90d6-0b82822fd51a.png)

**Comment by iErcann** [comment]
looks like it can't find node, do you have a discord? it's easier to talk

**Comment by genjikowa** [comment]
u have server discord?

**Comment by iErcann** [comment]
iercan#8283
